# Generated by Django 5.2.13 on 2026-04-11 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GLAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('in_review_range', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='PropertyReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_id', models.CharField(blank=True, max_length=20)),
                ('yardi_code', models.CharField(max_length=20, unique=True)),
                ('normalized_code', models.CharField(db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['normalized_code'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=40, unique=True)),
                ('source_file_name', models.CharField(blank=True, max_length=255)),
                ('source_file_size', models.BigIntegerField(blank=True, null=True)),
                ('source_content_type', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchaser', models.CharField(blank=True, max_length=255)),
                ('po_number', models.CharField(blank=True, max_length=100)),
                ('invoice_gl_code', models.CharField(blank=True, max_length=10)),
                ('invoice_gl_description', models.CharField(blank=True, max_length=255)),
                ('property_code_raw', models.CharField(blank=True, max_length=20)),
                ('property_code_normalized', models.CharField(blank=True, db_index=True, max_length=20)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('grand_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw_text', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('upload_batch_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('property_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.propertyreference')),
            ],
            options={
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField()),
                ('item_type', models.CharField(choices=[('product', 'Product'), ('shipping', 'Shipping'), ('discount', 'Discount'), ('fee', 'Fee')], default='product', max_length=20)),
                ('description', models.TextField()),
                ('normalized_description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('line_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('asin', models.CharField(blank=True, max_length=20)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('order_number', models.CharField(blank=True, max_length=40)),
                ('invoice_gl_code_hint', models.CharField(blank=True, max_length=10)),
                ('suggested_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('suggestion_reason', models.TextField(blank=True)),
                ('suggestion_candidates', models.JSONField(blank=True, default=list)),
                ('approval_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_gl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_line_items', to='invoices.glaccount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoices.invoice')),
                ('suggested_gl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_line_items', to='invoices.glaccount')),
            ],
            options={
                'ordering': ['invoice_id', 'line_number', 'id'],
                'unique_together': {('invoice', 'line_number')},
            },
        ),
    ]
