# Generated by Django 5.2.13 on 2026-04-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkUploadRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('total_files', models.PositiveIntegerField(default=0)),
                ('state', models.CharField(default='queued', max_length=20)),
                ('processed_files', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('current_file', models.CharField(blank=True, max_length=255)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('output_path', models.CharField(blank=True, max_length=255)),
                ('invoice_ids', models.JSONField(blank=True, default=list)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
