# Generated by Django 5.2.13 on 2026-04-12 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_bulkuploadrun'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BulkUploadRun',
        ),
    ]
