# Generated by Django 5.2.13 on 2026-04-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invoices", "0003_delete_bulkuploadrun"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertyreference",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
