# Generated by Django 5.2.13 on 2026-04-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_propertyreference_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicelineitem',
            name='approval_notes',
        ),
    ]
